### ISSUE TITLE
Compatibility Issues?

### ISSUE THREAD

**Issue by CoMMyz** [GeorgeHahn/DPIMangler#1]
Hi,

Thanks for this library i have been using it for the Viber application to make it work for High Res screens as it is unreadable without.

The new version released today no longer works with the library. The app launches but no change.
Can you please assist in any way?

Thanks

**Comment by GeorgeHahn** [comment]
I don't use it, but I'll take a peek if you zip up your install directory. Did the style change in this release? They may have switched from a native app to something html based.

**Comment by CoMMyz** [comment]
Exactly the same style :(
You can download it here http://www.commy.org/Viber.rar

Thanks

**Comment by GeorgeHahn** [comment]
I took a quick look and didn't see any definitive cause. Sadly, I can't run the application without doing a complete install, and I don't have a good VM set up for that right now.

Here are a few suggestions:
- Definitely complain to the Viber team
- Try setting the `QT_DEVICE_PIXEL_RATIO` environment variable. More [here](https://github.com/haiwen/seafile/issues/895#issuecomment-72356357) and [here](http://doc.qt.io/qt-5/highdpi.html).
- Fork the repo and hook SetProcessDPIAwareness [here](https://github.com/GeorgeHahn/DPIMangler/blob/master/dll_resources/dllmain.cpp).

**Comment by CoMMyz** [comment]
Setting 
QT_DEVICE_PIXEL_RATIO to a value of 2 (not 2.0) works perfectly!

Thank you!
